### ISSUE TITLE
Update Makefile to reflect the change in executable path

### ISSUE THREAD

**Issue by emanuelquerty** [emanuelquerty/bloggen#11]
After pull request #4 was merged, the path to the entry files changed from `cmd` to `cmd/bloggen`. However, the `Makefile` in root directory is still pointing the `cmd/*.go` when it should now be `cmd/bloggen/*.go` since all  files where moved down the tree to  the newly created directory  `bloggen`.

Also, the `run` and `preview` rules in makefile which use the `cmd/markdown` path should also be updated to `cmd/bloggen/markdown` path.

Thank you

**Comment by Antoineio** [comment]
:wave: 

Hello, in order to do my test in #9 
i needed to update the `Makefile` 

Can i be assigned to this issue ? :) 


```bash
[antoine@desktop /etc/projects/bloggen (bug/help-command)]$ rm -rf bin/bloggen 
[antoine@desktop /etc/projects/bloggen (bug/help-command)]$ make build
go build -o bin/bloggen cmd/bloggen/*.go
[antoine@desktop /etc/projects/bloggen (bug/help-command)]$ ./bin/bloggen 

Usage: bloggen [OPTION] --from [DIRECTORY]

Generates a site from a given DIRECTORY of markdowns.
DIRECTORY is the path to the folder that contains markdown files.

Available OPTIONS:
create      creates the site from DIRECTORY
preview     creates the site from DIRECTORY and starts a server to preview the generated site

Full documentation is available at <https://github.com/emanuelquerty/bloggen>
[antoine@desktop /etc/projects/bloggen (bug/help-command)]$ 
```
*i will create a new branch to include this changes*

**Comment by emanuelquerty** [comment]
@Antoineio Yes, you can assign assign yourself to this issue as well. I answered to your other comment on #9 that I had forgotten to send a request for you to be a collaborator but I have done that. Please read the last comment on that other issue, #9 which has more details.

Thank you

**Comment by Antoineio** [comment]
:wave:

Yes i see, i'm correctly able to issue myself this issue too
All work well thanks a lot :+1:

**Comment by emanuelquerty** [comment]
Good to know it works now 👌🏾
