### ISSUE TITLE
Fix help command 

### ISSUE THREAD

**Issue by emanuelquerty** [emanuelquerty/bloggen#9]
The `help` flag command is not working as intended.  It tries to create a website, which panics since it tries to do so with no path to a markdown directory specified. The intended behavior is to show the `usage` information.

Relevant files: `cmd/bloggen/main.go`

Relevant command:

```./bloggen -help``` or ```go run . -help```  if run from `cmd/bloggen` directory

**Comment by Antoineio** [comment]
Hello :wave: 
Can i try to work on this ? 
It's one of my first collaborations on an open-source project, and i'm a beginner in Golang
But i want to improve my skills in Golang so if you ok, i can try to work on this :)

**Comment by emanuelquerty** [comment]
Hello @Antoineio 👋 

Yes, you are more than welcome to work on this. I welcome any contribution ☺️ .

Before starting, please read the really short guidelines page on https://github.com/emanuelquerty/bloggen/blob/main/CONTRIBUTING.md

Go ahead and assign yourself to the issue so I know you will be working on it. Please, don't hesitate to let know if you need any help with the issue

**Comment by Antoineio** [comment]
@emanuelquerty 

Thanks a lot for your answer.
> Before starting, please read the really short guidelines

Sure ! :) 
> Go ahead and assign yourself to the issue

Unfortunately, i can't assign myself the issue :(

> Please, don't hesitate to let know if you need any help with the issue

Thank you, i keep you posted

**Comment by Antoineio** [comment]
@emanuelquerty 
Can you confirm me this result is what you expected : 
_Don't hesitate to tell me if i shouldn't provided a message who is that long_ :sweat_smile: 

### CASE NO OPTION PROVIDED

```bash

[antoine@desktop /etc/projects/bloggen (bug/help-command)]$ ./bin/bloggen 

Usage: bloggen [OPTION] --from [DIRECTORY]

Generates a site from a given DIRECTORY of markdowns.
DIRECTORY is the path to the folder that contains markdown files.

Available OPTIONS:
create      creates the site from DIRECTORY
preview     creates the site from DIRECTORY and starts a server to preview the generated site

Full documentation is available at <https://github.com/emanuelquerty/bloggen>
[antoine@desktop /etc/projects/bloggen (bug/help-command)]$ ./bin/bloggen --help
Error: --from flag is required

Usage: bloggen [OPTION] --from [DIRECTORY]

Generates a site from a given DIRECTORY of markdowns.
DIRECTORY is the path to the folder that contains markdown files.

Available OPTIONS:
create      creates the site from DIRECTORY
preview     creates the site from DIRECTORY and starts a server to preview the generated site

Full documentation is available at <https://github.com/emanuelquerty/bloggen>
[antoine@desktop /etc/projects/bloggen (bug/help-command)]$ ./bin/bloggen -help
Error: --from flag is required

Usage: bloggen [OPTION] --from [DIRECTORY]

Generates a site from a given DIRECTORY of markdowns.
DIRECTORY is the path to the folder that contains markdown files.

Available OPTIONS:
create      creates the site from DIRECTORY
preview     creates the site from DIRECTORY and starts a server to preview the generated site

Full documentation is available at <https://github.com/emanuelquerty/bloggen>
[antoine@desktop /etc/projects/bloggen (bug/help-command)]$ 
```

### CASE CREATE OPTION PROVIDED
```bash
[antoine@desktop /etc/projects/bloggen (bug/help-command)]$ ./bin/bloggen create 
Error: --from flag is required

Usage: bloggen [OPTION] --from [DIRECTORY]

Generates a site from a given DIRECTORY of markdowns.
DIRECTORY is the path to the folder that contains markdown files.

Available OPTIONS:
create      creates the site from DIRECTORY
preview     creates the site from DIRECTORY and starts a server to preview the generated site

Full documentation is available at <https://github.com/emanuelquerty/bloggen>
[antoine@desktop /etc/projects/bloggen (bug/help-command)]$ ./bin/bloggen create -help

Usage: bloggen [OPTION] --from [DIRECTORY]

Generates a site from a given DIRECTORY of markdowns.
DIRECTORY is the path to the folder that contains markdown files.

Available OPTIONS:
create      creates the site from DIRECTORY
preview     creates the site from DIRECTORY and starts a server to preview the generated site

Full documentation is available at <https://github.com/emanuelquerty/bloggen>
[antoine@desktop /etc/projects/bloggen (bug/help-command)]$ ./bin/bloggen create --help

Usage: bloggen [OPTION] --from [DIRECTORY]

Generates a site from a given DIRECTORY of markdowns.
DIRECTORY is the path to the folder that contains markdown files.

Available OPTIONS:
create      creates the site from DIRECTORY
preview     creates the site from DIRECTORY and starts a server to preview the generated site

Full documentation is available at <https://github.com/emanuelquerty/bloggen>
[antoine@desktop /etc/projects/bloggen (bug/help-command)]$ 

```

### CASE PREVIEW OPTION PROVIDED
```bash
[antoine@desktop /etc/projects/bloggen (bug/help-command)]$ ./bin/bloggen preview
Error: --from flag is required

Usage: bloggen [OPTION] --from [DIRECTORY]

Generates a site from a given DIRECTORY of markdowns.
DIRECTORY is the path to the folder that contains markdown files.

Available OPTIONS:
create      creates the site from DIRECTORY
preview     creates the site from DIRECTORY and starts a server to preview the generated site

Full documentation is available at <https://github.com/emanuelquerty/bloggen>
[antoine@desktop /etc/projects/bloggen (bug/help-command)]$ ./bin/bloggen preview -help

Usage: bloggen [OPTION] --from [DIRECTORY]

Generates a site from a given DIRECTORY of markdowns.
DIRECTORY is the path to the folder that contains markdown files.

Available OPTIONS:
create      creates the site from DIRECTORY
preview     creates the site from DIRECTORY and starts a server to preview the generated site

Full documentation is available at <https://github.com/emanuelquerty/bloggen>
[antoine@desktop /etc/projects/bloggen (bug/help-command)]$ ./bin/bloggen preview --help

Usage: bloggen [OPTION] --from [DIRECTORY]

Generates a site from a given DIRECTORY of markdowns.
DIRECTORY is the path to the folder that contains markdown files.

Available OPTIONS:
create      creates the site from DIRECTORY
preview     creates the site from DIRECTORY and starts a server to preview the generated site

Full documentation is available at <https://github.com/emanuelquerty/bloggen>

```
### CASE FLAG `--from` PROVIDED WITHOUT DIRECTORY 
```bash
[antoine@desktop /etc/projects/bloggen (bug/help-command)]$ ./bin/bloggen preview --from
flag needs an argument: -from
Usage of bloggen:
  -from value
    	the name of the directory that contains all markdown files
  -help
    	Display help
[antoine@desktop /etc/projects/bloggen (bug/help-command)]$ ./bin/bloggen create --from
flag needs an argument: -from
Usage of bloggen:
  -from value
    	the name of the directory that contains all markdown files
  -help
    	Display help
```

### NORMAL USAGE 

```bash
[antoine@desktop /etc/projects/bloggen/cmd/bloggen (bug/help-command)]$ /etc/projects/bloggen/bin/bloggen create --from markdown

Scaffolding your website in /etc/projects/bloggen/cmd/bloggen/build
Build directory created.

Downloading static assets...
Copied: css/style.css
Copied: img/house-image.avif
Copied: img/island.avif

Done.
[antoine@desktop /etc/projects/bloggen/cmd/bloggen (bug/help-command)]$ ls -la assets/css; ls -la assets/img/
total 16
drwxrwxr-x 2 antoine antoine 4096 mai   16 12:21 .
drwxrwxr-x 4 antoine antoine 4096 mai   16 12:21 ..
-rw-rw-r-- 1 antoine antoine 4449 mai   16 12:21 style.css
total 736
drwxrwxr-x 2 antoine antoine   4096 mai   16 12:21 .
drwxrwxr-x 4 antoine antoine   4096 mai   16 12:21 ..
-rw-rw-r-- 1 antoine antoine 151003 mai   16 12:21 house-image.avif
-rw-rw-r-- 1 antoine antoine 590399 mai   16 12:21 island.avif
[antoine@desktop /etc/projects/bloggen/cmd/bloggen (bug/help-command)]$ /etc/projects/bloggen/bin/bloggen preview --from markdown

Scaffolding your website in /etc/projects/bloggen/cmd/bloggen/build
Build directory created.

Downloading static assets...
Copied: css/style.css
Copied: img/house-image.avif
Copied: img/island.avif

Done.

Your site is available for preview on  http://localhost:3000/ 
```

**Comment by emanuelquerty** [comment]
@Antoineio Sorry I forgot to add you as collaborator so you can have permissions to add yourself to issues and send pull requests. ***I have sent you now a request to be added as collaborator***. 

***You should receive a request in your GitHub email and in your GitHub notifications tab*** . All you need to do is accept and you should then be able to assign yourself to this issue and create pull requests.

**Comment by emanuelquerty** [comment]
Everything is pretty much correct. There is only a tiny change I would like for this cases bellow for ` ./bin/bloggen --help` and  
` ./bin/bloggen -help`


> @emanuelquerty Can you confirm me this result is what you expected : _Don't hesitate to tell me if i shouldn't provided a message who is that long_ 😅
> 
> ### CASE NO OPTION PROVIDED
> ```shell
> [antoine@desktop /etc/projects/bloggen (bug/help-command)]$ ./bin/bloggen --help
> Error: --from flag is required
> 
> Usage: bloggen [OPTION] --from [DIRECTORY]
> 
> Generates a site from a given DIRECTORY of markdowns.
> DIRECTORY is the path to the folder that contains markdown files.
> 
> Available OPTIONS:
> create      creates the site from DIRECTORY
> preview     creates the site from DIRECTORY and starts a server to preview the generated site
> 
> Full documentation is available at <https://github.com/emanuelquerty/bloggen>
> [antoine@desktop /etc/projects/bloggen (bug/help-command)]$ ./bin/bloggen -help
> Error: --from flag is required
> 
> Usage: bloggen [OPTION] --from [DIRECTORY]
> 
> Generates a site from a given DIRECTORY of markdowns.
> DIRECTORY is the path to the folder that contains markdown files.
> 
> Available OPTIONS:
> create      creates the site from DIRECTORY
> preview     creates the site from DIRECTORY and starts a server to preview the generated site
> 
> Full documentation is available at <https://github.com/emanuelquerty/bloggen>
> ```

It should not print  `Error: --from flag is required` before printing the usage for this two cases since here the user just wants to read the usage. For all other cases, it's alright to print that.

Other than that, everything looks as the expected behavior. Once you make that change, you can submit the pull request 😃

**Comment by Antoineio** [comment]
:wave:

Thanks for adding me as a collaborator; i'm correctly able to assign myself the issue :+1: 
> It should not print Error: --from flag is required before printing the usage for this two cases since here the user just wants to read the usage. For all other cases, it's alright to print that.
Other than that, everything looks as the expected behavior. Once you make that change, you can submit the pull request 😃

Ok, i will make the change and submit a pull request

**Comment by emanuelquerty** [comment]
Yeah of course, good to know that worked out. 

And that sounds good.
